FROM python:3.8.5-slim

# set working directory
WORKDIR /app

COPY atmospherex_transformer_base/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY atmospherex_transformer_base .

ENV PYTHONPATH=/app

RUN chmod +x test-script.sh

CMD ["/app/test-script.sh"]
