[tool.poetry]
name = "atmosphere"
version = "v4.1.0"
description = "The atmosphere python SDK including multiple modules to help with setting up activities, transformers and more."
authors = ["Ambiata <atmosphere@ambiata.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.8,<3.12"
apscheduler = ">=3.10.1"
fastapi = ">=0.95.0"
httpx = ">=0.23.3"
pyjwt = ">=2.6.0"
pyyaml = ">=6.0"
simplejson = ">=3.18.4"
uvicorn = ">=0.21.1"

[tool.poetry.group.dev.dependencies]
autoflake = "1.4"
autopep8 = "1.6.0"
black = "22.3.0"
coverage = "6.3.2"
httpretty = "1.1.4"
isort = "5.10.1"
mypy-extensions = "0.4.3"
pylint = "2.13.5"
pytest = "7.1.1"
pytest-cov = "3.0.0"
pytest-env = "0.6.2"
requests-mock = "1.9.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
