name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-base-activity:
    name: Test base activity
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run the tests on the base activity
        id: test-activity-base
        run: |
          docker build -f Dockerfile-activity-base-test -t activity-base-test .
          docker run activity-base-test

  test-base-transformer:
    name: Test base transformer
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run the tests on the base transformer
        id: test-transformer-base
        run: |
          docker build -f Dockerfile-transformer-base-test -t transformer-base-test .
          docker run transformer-base-test


  release:
    name: Create new release
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: [ test-base-activity, test-base-transformer ]
    steps:
    - name: Dry bump version and push tag
      id: dry-bump-tag
      if: github.event_name == 'push' &&  github.ref == 'refs/heads/master'
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
    - name: Setup git config
      if: github.event_name == 'push' &&  github.ref == 'refs/heads/master'
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "info@ambiata.com"
    - name: Commit the new version of the python package
      if: github.event_name == 'push' &&  github.ref == 'refs/heads/master'
      env:
        NEW_TAG: ${{ steps.dry-bump-tag.outputs.new_tag }}
      run: |
        echo "# The version is auto-generated by the CI/CD pipeline" > VERSION
        echo "${NEW_TAG}" >> VERSION
        git add atmospherex_demo_sushi/VERSION
        git commit -m "[tag] version ${NEW_TAG}"
        git push origin master
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bump version and push tag
      id: push-tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
