name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: Install, lint and test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run the linter
        run: |
          ./scripts/lint.sh

      - name: Run the test
        run: |
          ./scripts/test.sh

  testouille:
    name: testouille
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: git config
      run: |
        git config --global --add safe.directory /github/workspace

    - name: Dry bump version and push tag
      id: dry-bump-tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
  
  tag:
    name: Create new release
    runs-on: ubuntu-20.04
    if: github.event_name == 'push' &&  github.ref == 'refs/heads/main'
    needs: [ test ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Dry bump version and push tag
      id: dry-bump-tag
      uses: anothrNick/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true

    - name: Commit the new version of the python package
      env:
        NEW_TAG: ${{ steps.dry-bump-tag.outputs.new_tag }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "info@ambiata.com"
        echo "# The version is auto-generated by the CI/CD pipeline" > atmosphere/VERSION
        echo "${NEW_TAG}" >> atmosphere/VERSION
        git add atmosphere/VERSION
        git commit -m "[tag] version ${NEW_TAG}"
        git push origin main

    - name: Push tag
      id: push-tag
      uses: anothrNick/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
