---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)-23.23s %(levelname)-5.5s %(name)s: %(message)s"
filters:
  stderr_filter:
    (): atmospherex_activity_base.logger_setup.StdErrFilter
  stdout_filter:
    (): atmospherex_activity_base.logger_setup.StdOutFilter
  health_check_filter:
    (): atmospherex_activity_base.logger_setup.HealthCheckFilter

handlers:
  stdout:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    filters: [ stdout_filter, health_check_filter ]
    stream: ext://sys.stdout

  stderr:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    filters: [ stderr_filter ]
    stream: ext://sys.stderr

loggers:
  atmosphere_api:
    level: INFO
  uvicorn:
    level: INFO

root:
  level: INFO
  handlers: [ stdout, stderr ]